export const upcomingEvents = [
  {
    id: 1,
    title: "Event 1",
    description: "This is event 1",
    date: "2020-01-01",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
  {
    id: 2,
    title: "Event 2",
    description: "This is event 2",
    date: "2020-01-02",
    time: "12:00",
    location_name: "Sporting Club",
    city: "Mecca",
    location_image:
      "https://images.unsplash.com/photo-1621635574078-c6068e1179fa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
  },
  {
    id: 3,
    title: "Event 3",
    description: "This is event 3",
    date: "2020-01-03",
    time: "12:00",
    location_name: "Nofa Riyadh",
    city: "Riyadh Makkah Highway",
    location_image: "https://iili.io/r0Lu29.jpg",
  },
  {
    id: 4,
    title: "Event 4",
    description: "This is event 4",
    date: "2020-01-04",
    time: "12:00",
    location_name: "Dirab Golf & Country Club",
    city: "Riyadh",
    location_image: "https://iili.io/r0LIr7.jpg",
  },
  {
    id: 5,
    title: "Event 5",
    description: "This is event 5",
    date: "2020-01-05",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
  {
    id: 6,
    title: "Event 6",
    description: "This is event 6",
    date: "2020-01-06",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
];
export const previousEvents = [
  {
    id: 1,
    title: "Previous Event 1",
    description: "This is Previous event 1",
    date: "2020-01-01",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
  {
    id: 2,
    title: "Previous Event 2",
    description: "This is Previous event 2",
    date: "2020-01-02",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
  {
    id: 3,
    title: "Previous Event 3",
    description: "This is Previous event 3",
    date: "2020-01-03",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
  {
    id: 4,
    title: "Previous Event 4",
    description: "This is Previous event 4",
    date: "2020-01-04",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
  {
    id: 5,
    title: "Previous Event 5",
    description: "This is Previous event 5",
    date: "2020-01-05",
    time: "12:00",
    location_name: "Al Ula Desert",
    city: "Al Ula",
    location_image: "https://iili.io/r0LA7e.md.jpg",
  },
];
